apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-labeled
  labels:
    app: nginx
    environment: dev
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80